name: tugas_akhir_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  contentsize_tabbarview: ^0.0.2
  cupertino_icons: ^1.0.6
  delightful_toast: ^1.1.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  # flutter_barcode_scanner: ^2.0.0
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  get_it: ^7.7.0
  go_router: ^14.1.1
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.8
  http: ^1.2.1
  iconsax: ^0.0.8
  image: ^4.1.7
  image_picker: ^1.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  location: ^7.0.0
  mobile_scanner: ^5.1.1
  persistent_bottom_nav_bar_v2: ^5.3.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  sidebarx: ^0.17.1
  slide_countdown: ^1.6.1
  timelines: ^0.1.0
  webview_flutter: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
