name: tugas_akhir_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  autoscale_tabbarview: ^1.0.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  delightful_toast: ^1.1.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.1
  http: ^1.2.1
  iconsax: ^0.0.8
  image: ^4.1.7
  image_picker: ^1.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sidebarx: ^0.17.1

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
